### ISSUE TITLE
Mise en place du repo

### ISSUE THREAD

**Issue by KyllianBeguin** [KyllianBeguin/L3L4B#1]
Salut les labers 👋
Pour cette première issue, je vous propose d'aborder l'orga du repo.  

## Proposition
- Un dossier pour tout ce qui est organisation, qui contiendra
  - Un lien vers le Klaxoon (dans un readme)
  - La charte du lab
  - Un dossier média (bannières, logo du lab, etc.)
  - Une synthèse des expérimentations en cours
- Un dossier qui contiendra toutes les expérimentations en cours
  - Un dossier par expérimentation
  - Un dossier pour la mise en place d'el Projecto Lider ;)

## Pourquoi ?
- Pour pas que ça soit le bordel sur le repo, puisque j'aimerais que tout soit centralisé ici.
- Pour que ça nous motive à avancer dans les expérimentations !

**Comment by FlorianD78** [comment]
Bonjour,
Plein de bonnes idées intéressantes.
Je pense qu'un README.md + dossier média sera suffisant.
Une bonne table des matières et c'est good.
Puis un dossier 'expérimentations':
- expérience-1
  - README.md
...

Un truc dans le genre.

On va utiliser la fonctionnalité "project" de GH?

Dans l'attente de vous lire ;)

**Comment by KyllianBeguin** [comment]
Je pense que c'est good aussi. Je vais mettre ça en place 🚀
Pour le "project", ça peut carrément se faire, histoire de se faire la main avec ! Tu t'en charge ?

**Comment by FlorianD78** [comment]
Yes!

**Comment by KyllianBeguin** [comment]
J'ai commencé la mise en place, sur la base de ce qu'on s'est dit.
Étant donnée que les expérimentations seront aussi des tests d'outils, je pense que l'on pourrait avoir des dossiers du genre `20-Kubernetes`

**Comment by KyllianBeguin** [comment]
### Session du 2023/03/06
Changement du nom : le lab >> L3L4B
MaJ du Readme avec une description de L3L4B
Rédaction du manifeste L3L4B
